### PR TITLE
Update description in composer.json

### PR DESCRIPTION
**Pull request by manicki**
I've just noticed that `composer.json` is missing description.
I've only copied description from github repository and now ping @tobijat and @jakobw to list some proper keywords that should be put there.
Suggesting a better/other description will also be appreciated.

### CODE REVIEW

**Comment by jakobw** [comment]
`["foo", "bar"]` sounds good enough :D
How about `["Phragile", "Phabricator", "Agile", "Sprints", "Visualization", "Burndown"]` or something like that?

**Comment by WMDE-Fisch** [comment]
Whoaaaa! It's a Jakob! :-]

**Comment by manicki** [comment]
Thanks @jakobw. Everybody feel free to adjust keywords/description.

**Comment by WMDE-Fisch** [comment]
How about `Burnup` as well? And the killer buzz word `SCRUM` ?

**Comment by manicki** [comment]
I think now I've added all requested keywords.

**Comment by WMDE-Fisch** [comment]
Tobi approved ;-)

**Pull request merged**
