### PR TITLE
updating libraries used in composer.lock

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
fixes several problems I and other encountered with the current libraries uses
is also needed for updated libphutil

also fixes https://phabricator.wikimedia.org/T117324

### CODE REVIEW

**Comment by wmde-manicki** [comment]
+1 for the change
It is unclear for me how does this fixes the problem mentioned in the phab ticket, though. Some DB-stuff got changed and now empty string defult to zero?
Using dependencies defined on the current master I couldn't reproduced the error described in that ticket too, so it's all strange. But I'm totally fine with the fact that this change fixes that problem :)

**Comment by wmde-manicki** [comment]
Breaking news: I've managed to replicate the problem on master

**Comment by WMDE-Fisch** [comment]
Strange now I cant replicated it anymore :-)

**Comment by wmde-manicki** [comment]
So the problem with `Integrity constraint violation: 1048 Column 'ignore_estimates' cannot be null ` appeared after setting `sql_mode=STRICT_ALL_TABLES` in mysql config. It looks clearly like a problem with passing null to non-null-allowed column. Apparently some change in some dependency fixes something related to that.
Strangely enough, problems reported in https://phabricator.wikimedia.org/T117323 do not appear any more even using `STRICT_ALL_TABLES` when I have updated dependencies but not applied patches from: https://github.com/wmde/phragile/pull/177 :)

**Comment by WMDE-Fisch** [comment]
Hmm super strange. But default values are good anyway I would say :-)

**Pull request merged**
