### PR TITLE
Acceptance ci

### PR DESCRIPTION
**Pull request by jakobw**
Task: https://phabricator.wikimedia.org/T100329

Woohooo, we can haz Behat tests on Travis! \o/

What this does:
- install a clean Phragile instance and start it using the built-in PHP web server
- sets up Phabricator
- gets around annoying Phabricator configuration (user creation, auth token generation, creating Phragile OAuth app etc) by importing a SQL dump that contains only the minimal configuration
- awkwardly starts nginx from a custom configuration
- removed HHVM and PHP 7 for now

### CODE REVIEW

**Comment by WMDE-Fisch** [comment]
You cold clean the commit history before we spam this into master :-) - Just put it all in one commit I would say. - Apart from that nice job :100: !

**Comment by jakobw** [comment]
Done!

**Comment by wmde-manicki** [comment]
OMG awesome!

**Comment by wmde-manicki** [comment]
@jakow: here is the change that [fixes](https://travis-ci.org/wmde/phragile/builds/105154989) PHP7 build: https://github.com/wmde/phragile/blob/ae110e3f6a7ceac4af3c5da1f5a5e76f9b071b29/build/start_fpm.sh#L2-L5

**Comment by jakobw** [comment]
Nice, PHP 7 is now also working!

**Pull request merged**
