### PR TITLE
Show burnup or burndown depending on the url fragment.

### PR DESCRIPTION
**Pull request by jakobw**
Task: https://phabricator.wikimedia.org/T119186

Putting #burnup at the end of a Phragile sprint URL will now show the burnup chart right away.

### CODE REVIEW

**Comment by tobijat** [comment]
It was not written directly in the task, but I think it should also add the #burnup or #burndown to the URL when I click the tabs. So I'm able to reload the page and see the same tab immediately.

**Comment by wmde-manicki** [comment]
Just tested it locally and apart from @tobijat said it looks and works good.

**Comment by jakobw** [comment]
Updated. In case you're wondering what's up with the weird `#!`syntax - it keeps the browser from jumping to the burndown chart when #burndown is selected.

**Comment by wmde-manicki** [comment]
Works for me! I'd merge this unless @tobijat has some further remarks.

**Comment by WMDE-Fisch** [comment]
+1 as well

**Comment by wmde-manicki** [comment]
@tobijat just said he has no further objections

**Pull request merged**
